sudo: false
language: node_js

node_js:
  - "6"
  - "8"
  - "10"

os:
  - osx
  - linux

install:
  - travis_retry yarn install

script:
  - uname -a
  - node --version
  - npm --version
  - npm run lint
  - npm run cover
  - npm run browser
  - npm run report
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
