sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "stable"
script:
  - node --version
  - npm --version
  - npm run ci-lint
  - npm run cover
  - npm run browser
  - npm run report
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
